name: KringleCrate
main: me.benrobson.kringlecrate.KringleCrate
version: 1.0.0
api-version: 1.21
description: A Secret Santa plugin for Minecraft.
commands:
  kc:
    description: Main command for KringleCrate.
    usage: /<command>
permissions:
  kringlecrate.redeem:
    description: Allows players to redeem their gifts.
    default: true
  kringlecrate.override:
    description: Allows players to override redemption rules.
    default: op
